[package]
name = "cueball-tcp-stream-connection"
version = "0.1.1"
authors = ["Kelly McLaughlin <kelly.mclaughlin@joyent.com>"]
edition = "2018"

[dependencies]
cueball = { git = 'https://github.com/joyent/rust-cueball', tag = "v0.2.1" }
